### ISSUE TITLE
BadAuthentication When updating

### ISSUE THREAD

**Issue by hako** [onyxbits/Raccoon#22]
When I run ```java -jar raccoon-3.5.jar -a ../Raccoon/archives/default -u``` I'm starting to get this error more frequently.

```java 
com.akdeniz.googleplaycrawler.GooglePlayException: Error=BadAuthentication
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:582)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:540)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:519)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.login(GooglePlayAPI.java:228)
	at de.onyxbits.raccoon.App.createConnection(App.java:132)
	at de.onyxbits.raccoon.CliService.doUpdate(CliService.java:139)
	at de.onyxbits.raccoon.CliService.run(CliService.java:115)
	at de.onyxbits.raccoon.App.main(App.java:83)
```

I've definitely checked my Google Account and Password and it's definitely valid, I can login through the app.

Update: Just confirmed it looks like some sort of glitch at Google's end. Not sure what's causing it. Sometimes it works sometimes it doesn't.

**Comment by onyxbits** [comment]
Several possibilities for this one:

* You are streaming videos or downlaoding files in the background -> Timeout on Login
* You have been using the same account on multiple apps/devices -> Google has started tracking from where you log in and might think that your account got stolen -> You have to log in on their website and tell them it's ok.
* You are using two factor auth (well, that's not the problem here) -> You need to setup an application specific password.
