### ISSUE TITLE
GooglePlayException when searching for apps in GUI

### ISSUE THREAD

**Issue by craftyguy** [onyxbits/Raccoon#35]
I have 2-step auth enabled on my account and attempted to use a generated app password to log in with Raccoon. It seems to be successful initially, however I receive the following exception when I try to search for anything:

`
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=vrgb
java.util.concurrent.ExecutionException: com.akdeniz.googleplaycrawler.GooglePlayException: 31Error retrieving information from server. [RH-02]
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at javax.swing.SwingWorker.get(SwingWorker.java:602)
    at de.onyxbits.raccoon.gui.SearchWorker.done(SearchWorker.java:199)
    at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
    at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.akdeniz.googleplaycrawler.GooglePlayException: 31Error retrieving information from server. [RH-02]
    at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:585)
    at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeGet(GooglePlayAPI.java:575)
    at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeGETRequest(GooglePlayAPI.java:474)
    at com.akdeniz.googleplaycrawler.GooglePlayAPI.search(GooglePlayAPI.java:268)
    at de.onyxbits.raccoon.gui.SearchWorker.doQuerySearch(SearchWorker.java:139)
    at de.onyxbits.raccoon.gui.SearchWorker.doInBackground(SearchWorker.java:111)
    at de.onyxbits.raccoon.gui.SearchWorker.doInBackground(SearchWorker.java:38)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`

When this occurs, the GUI app prints "authentication error". I am using Raccoon 3.7.

**Comment by onyxbits** [comment]
Hm...
looks like you'll need an account without 2 step auth then.

Am Donnerstag, den 04.08.2016, 19:20 -0700 schrieb clayton craft:

**Comment by craftyguy** [comment]
Hmm, that means re-purchasing some apps that are already associated with my google account. The Raccoon docs indicate accounts with two-step auth will work if I use an app specific password (which I am), so either google changed something to break that and the Raccoon docs need to be updated to reflect that this will no longer work (or Raccoon fixed to account for whatever change Google made), or Raccoon is busted in some other way.

**Comment by craftyguy** [comment]
Turns out this only happens when I use the Android ID from my device. If  I let Raccoon generate a bogus ID and use it with my real Google account (yes, against your warnings), then it works fine. There seems to be an issue with using a real Android ID with a real Google Account that has 2-step auth enabled.
